version: '3.8'
services:
  elasticsearch:
    image: 'elasticsearch:7.11.1'
    hostname: elasticsearch
    restart: unless-stopped
    ports:
      - '9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    # volumes:
    #   - './vol/elasticsearch/data:/usr/share/elasticsearch/data'
    #   - './vol/elasticsearch/logs:/usr/share/elasticsearch/logs'
    networks:
      - elk
  cortex:
    build:
      context: cortex
    restart: unless-stopped
    user: root
    command: --no-config
    environment:
      - 'JOB_DIRECTORY=${JOB_DIRECTORY}'
    volumes:
      # - './vol/cortex/application.conf:/etc/cortex/application.conf'
      - '${JOB_DIRECTORY}:${JOB_DIRECTORY}'
      - '/var/run/docker.sock:/var/run/docker.sock'

    ports:
      - '9001:9001'
    networks:
      - elk
  thehive:
    build:
      context: thehive
    image: 'thehiveproject/thehive4:latest'
    container_name: thehive4
    restart: unless-stopped
    depends_on:
      - elasticsearch
    user: root
    ports:
      - '9000:9000'
    volumes:
      # - ./vol/thehive/application.conf:/etc/thehive/application.conf
      - ./vol/thehive/db:/opt/thp/thehive/db
      - ./vol/thehive/index:/opt/thp/thehive/index
      - ./vol/thehive/data:/opt/thp/thehive/data
    command: --no-config
    networks:
      - elk
  elasalert:
    build:
      context: "./elasalert2"
    restart: unless-stopped
    command: --verbose
    user: root
    ports:
      - 8098:8098
    environment:
      - ES_HOST=elastic.pfasoc.online
      - ES_PORT=9200

    networks:
      - elk

networks:
  elk:
    name: elk
